### PR TITLE
Minor edits to markdown file

### PR DESCRIPTION
**Pull request by JoshOBrien**

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks. I specifically want to mention "documents folder" because many people don't know that this is considered home in R. Most other software treats the parent directory of documents as home.

**Comment by JoshOBrien** [comment]
Yikes. That's unfortunate. Since I have forever set the Windows user variable `HOME` to `C:\Users\Josh`, I had forgotten that `C:\Users\Josh\Documents` is in the list of places that R searches while attempting to determine the "home directory". 

[R for Windows FAQ 2.14](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#What-are-HOME-and-working-directories_003f) is very good on this subject. Mightn't it be more accurate to advise users to place `.Renviron` in their home directory, the location of which can found by typing `Sys.getenv("R_USER")` from within R? (I worry about instructing folks to place `.Renviron` in their Documents folder, since that may or may not actually be the directory that R considers to be their home directory.)

**Comment by jeroen** [comment]
Merged via https://github.com/r-windows/docs/commit/fb05dc543a0c94404c5826fcf1da8bc4cb57e12b

**Comment by jeroen** [comment]
I should actually merge this file with the [readme.md] because it duplicates some of this text.

**Pull request closed without merging**
